import React from "react";
import { Link } from "react-router-dom";

const HomePage = () => {
  return (
    <div className="home-page">
      {/* Hero Section */}
      <section className="hero-legal">
        <div className="hero-content-legal">
          <div className="hero-text">
            <h1 className="hero-title-legal">
              Stop Filing <span className="text-red">Hallucinated Citations</span>
            </h1>
            <p className="hero-subtitle-legal">
              Upload any legal brief and get instant validation of every case citation. Catch fabricated 
              cases before they embarrass you in court or help you challenge opposing counsel's 
              questionable citations.
            </p>
            
            <div className="alert-box">
              <div className="alert-icon">⚠️</div>
              <div className="alert-content">
                <strong>Breaking:</strong> 157 documented US legal cases involving AI hallucinations.
                <br />
                <span className="alert-sub">Recent example: "New Court of Appeals ordered 6 hours of mandatory ethics training for lawyer 
                who filed 'fake hallucinated cases'" - June 2024</span>
              </div>
            </div>

            <div className="hero-actions-legal">
              <Link to="/app" className="btn btn-primary-legal">
                Check Citations Now
              </Link>
              <button className="btn btn-secondary-legal">
                Watch Demo
              </button>
            </div>
          </div>
          
          <div className="hero-visual">
            <div className="citation-validation-demo">
              <div className="demo-item verified">
                <span className="citation">Roe v. Wade, 410 U.S. 113 (1973)</span>
                <span className="status verified">✓ Valid</span>
              </div>
              <div className="demo-item warning">
                <span className="citation">Smith v. OpenAI, 456 F.3d 789 (9th Cir. 2023)</span>
                <span className="status warning">⚠ Fabricated</span>
              </div>
              <div className="demo-item verified">
                <span className="citation">Brown v. Board, 347 U.S. 483 (1954)</span>
                <span className="status verified">✓ Valid</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Crisis Statistics */}
      <section className="crisis-section">
        <div className="crisis-container">
          <h2 className="crisis-title">The Crisis is Accelerating in US Courts</h2>
          <p className="crisis-subtitle">
            AI tools are creating convincing but fake legal citations at an unprecedented scale. US 
            lawyers are facing real sanctions for AI-generated hallucinations.
          </p>
          
          <div className="stats-grid">
            <div className="stat-box">
              <div className="stat-number">157</div>
              <div className="stat-label">US Cases Documented</div>
              <div className="stat-desc">Legal decisions involving AI hallucinations</div>
            </div>
            <div className="stat-box">
              <div className="stat-number">8.9M</div>
              <div className="stat-label">Citations in Database</div>
              <div className="stat-desc">US legal opinions we validate against</div>
            </div>
            <div className="stat-box">
              <div className="stat-number">Daily</div>
              <div className="stat-label">Database Updates</div>
              <div className="stat-desc">Continuously growing with new decisions</div>
            </div>
            <div className="stat-box">
              <div className="stat-number">30 sec</div>
              <div className="stat-label">Validation Time</div>
              <div className="stat-desc">To check every citation in your brief</div>
            </div>
          </div>
        </div>
      </section>

      {/* Recent Cases */}
      <section className="cases-section">
        <div className="cases-container">
          <h3 className="cases-title">Recent US Cases:</h3>
          <div className="cases-list">
            <div className="case-item">
              <strong>Mata v. Avianca (S.D.N.Y. 2023)</strong> - The Original AI Hallucination Case
              <p>Lawyer fined $5000 with six non-existent cases generated by ChatGPT, leading to $5,000 sanctions and national headlines. 
              "The Court is presented with an unprecedented circumstance." Federal Judge sanctions for AI-generated fake cases.</p>
            </div>
            
            <div className="case-item">
              <strong>Bochetto Eating & WORKING MANS v. Job Cleveland (Texas CA, June 2023)</strong>
              <p>Court sanctioned for "two fabricated cases" - Lawyer is required to attend 6 hours training An AI tool 
              "hallucinated at least 2 case citations that do not exist and could not be located by the court nor counsel," requiring no informational.</p>
            </div>
            
            <div className="case-item">
              <strong>Growing Pattern Across Federal and State Courts</strong>
              <p>A survey of 9 jurisdictions now showing evidence of AI use and implementing sanctions for fabricated citations. 
              Federal, state and district level courts have required additional verification, prompting enhanced citation verification 
              requirements in many jurisdictions.</p>
            </div>
          </div>
          
          <p className="cases-footer">
            We validate against 8.9 million US legal opinions, updated daily with new federal and state court decisions.
          </p>
        </div>
      </section>

      {/* Solution Steps */}
      <section className="solution-section">
        <div className="solution-container">
          <h2 className="solution-title">The Solution is Simple</h2>
          <p className="solution-subtitle">
            Upload any brief, get instant validation. Strike Cite checks every citation against 
            authoritative legal databases in seconds.
          </p>
          
          <div className="steps-grid">
            <div className="step-item">
              <div className="step-number">1</div>
              <h4>Upload Your Brief</h4>
              <p>Drag and drop any PDF, Word doc, or paste text directly. Works with your 
              briefs or opposing counsel's filings.</p>
              <div className="step-visual">
                <div className="upload-demo">📄 PDF Upload</div>
              </div>
            </div>
            
            <div className="step-item">
              <div className="step-number">2</div>
              <h4>Instant Validation</h4>
              <p>We automatically check every citation against our comprehensive database of 
              8.9 million US legal opinions, updated daily with new federal and state 
              court decisions.</p>
              <div className="step-visual">
                <div className="validation-examples">
                  <div className="example valid">
                    <span>Roe v. Wade, 410 U.S. 113 (1973)</span>
                    <span className="check">✓ Valid</span>
                  </div>
                  <div className="example invalid">
                    <span>Fake v. Citation, 999 U.S. 999</span>
                    <span className="cross">✗ Fabricated</span>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="step-item">
              <div className="step-number">3</div>
              <h4>Get Results</h4>
              <p>See exactly which citations are valid, invalid, or hallucinated. Get case 
              names, courts, and dates for verification.</p>
              <div className="step-visual">
                <div className="results-preview">
                  <div className="result-summary">Citations validated in 1.5 seconds</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Protection Section */}
      <section className="protection-section">
        <div className="protection-container">
          <h2 className="protection-title">Protect Against Sophisticated AI Deception</h2>
          <p className="protection-subtitle">
            Modern AI hallucinations aren't obvious fakes - they're convincing fabrications that can 
            fool experienced lawyers.
          </p>
          
          <div className="protection-grid">
            <div className="protection-item">
              <h4>Real AI Hallucination Patterns We Detect:</h4>
              <div className="pattern-examples">
                <div className="pattern">
                  <strong>Mixed Real/Fake Citations</strong>
                  <p>Real case numbers with fabricated case names, like "Fake case name" + "the cited case shows 'the case 
                  name in the actual US Legal Code would be different case name.'"</p>
                </div>
                <div className="pattern">
                  <strong>Plausible Context</strong>
                  <p>Fabricated cases with realistic legal reasoning that appears legitimate until checked 
                  against authoritative.</p>
                </div>
              </div>
            </div>
            
            <div className="protection-item">
              <h4>Authority Impersonation</h4>
              <p>Citations "from the US federal" - AI creating case-precedent from real 
              and authoritative sounds that reference fabricated "precedent"</p>
              
              <h4>Case Name Swapping</h4>
              <p>Real citations with wrong case names - like citing "Marley v. Straw, 419 U.S. 219" 
              when the actual case at that cite is different.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Trust Indicators */}
      <section className="trust-section">
        <div className="trust-container">
          <div className="trust-item">
            <div className="trust-icon">⚖️</div>
            <h4>Before You File</h4>
            <p>Check your briefs before filing to avoid embarrassing citations, sanctions, or missed opportunities.</p>
          </div>
          <div className="trust-item">
            <div className="trust-icon">🎯</div>
            <h4>Challenge Opponents</h4>
            <p>Quickly validate opposing counsel's citations. The famous Matter v. Avianca case showed how AI-generated fake cases can slip through.</p>
          </div>
          <div className="trust-item">
            <div className="trust-icon">🛡️</div>
            <h4>Professional Competence</h4>
            <p>Federal courts are updating local rules to address AI liability. Professional competence may now include citation verification as standard practice.</p>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="final-cta">
        <div className="cta-container">
          <h2 className="cta-title">Don't Be the Next Case Study</h2>
          <p className="cta-text">
            With 157 documented US cases of AI hallucination in legal practice and new sanctions 
            happening regularly, citation validation isn't optional anymore - it's essential professional 
            protection.
          </p>
          
          <div className="testimonial">
            <blockquote>
              "It is never acceptable to rely on software or technology—no matter how advanced—without reviewing 
              and verifying the information."
            </blockquote>
            <cite>Texas Court of Appeals, Jose Cruz (Ordering 6 hours of mandatory ethics training)</cite>
          </div>
          
          <Link to="/app" className="btn btn-final-cta">
            Validate Your Citations Now - Free →
          </Link>
          
          <p className="cta-disclaimer">
            Trusted by legal professionals nationwide.
          </p>
        </div>
      </section>
    </div>
  );
};

export default HomePage;